[tool.poetry]
name = "rdflib-ocdm"
version = "1.0.2"
description = ""
authors = ["arcangelo7 <arcangelomas@gmail.com>"]
license = "ISC"
readme = "README.md"
packages = [{include = "rdflib_ocdm"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
rdflib = "^6.2.0"
oc-ocdm = "^9.1.1"
sparqlwrapper = "^2.0.0"
redis = "^4.5.5"
time-agnostic-library = "^4.6.14"


[tool.poetry.group.dev.dependencies]
coverage = "^7.2.3"
coverage-badge = "^1.1.0"
isort = "^6.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
